version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-liveroom
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: w7517142w
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis-liveroom
    ports:
      - "6379:6379"


volumes:
  pgdata: